version: '3'
services:
  web:
    build: ./web
    container_name: web
    expose:
      - 5000
    networks:
      - nginx_network
    ports:
      - 5000:5000

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - nginx_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  nginx_network:
    driver: bridge
